mongo-container:
  image: mongo:3.4.2
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootPass
  ports:
    - "27017:27017"
  volumes:
    - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  command: mongod
