version: '3.3'

services:
  kafka:
    image: landoop/fast-data-dev
    environment:
      - ADV_HOST=127.0.0.1
      - BROWSECONFIGS=1
    volumes:
      - ~/localstack/landoop/data/:/data/
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    networks:
      - api-network
  mongo-container:
    image: mongo:3.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
    networks:
      - api-network

networks:
  api-network:

